version: '3'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    tty: true
    container_name: web
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    depends_on:
      - db
